package tdlm;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @co-author Chenxing He
 * @version 1.0
 */
public enum GLGLPropertyType {
   
    /* THESE ARE THE NODES IN OUR APP */
    TDLM_MAIN_BORDER_PANE,
    TDLM_WORK_SPACE_PANE,
    TDLM_SMALL_WORK_SPACE_PANE,
    TDLM_TOOL_PANE,
    TDLM_SHAPE_PANE,
    TDLM_FONT_PANE,
    TDLM_FIRST_FONT_PANE,
    TDLM_BORDER_BOX,
    TDLM_BORDER_THICKNESS_LABEL,
    TDLM_BORDER_RADIUS_LABEL,
    TDLM_BORDER_COLOR_LABEL,
    
    TDLM_COLOR_GRADIENT,
    TDLM_COLOR_GRADIENT_LABEL,
    TDLM_FOCUS_ANGLE_LABEL,
    TDLM_FOCUS_DISTANCE_LABEL,
    TDLM_CANTER_X_LABEL,
    TDLM_CANTER_Y_LABEL,
    TDLM_RADIUS_LABEL,
    TDLM_CYCLE_METHOD_LABEL,
    TDLM_STEP_0_COLOR_LABEL,
    TDLM_STEP_1_COLOR_LABEL,
    TDLM_FOUCS_DISTANCE_Slider,
    TDLM_CANTER_X_Slider,
    TDLM_CANTER_Y_Slider,
    TDLM_RADIUS_Slider,
    
    
    
    
    
    // THIS IS THE TDLM WORKSPACE PANE
    TDLM_PANE,
    TDLM_TO_DO_LIST_LABEL,
    

       
    // ITEMS EDITING
    TDLM_ITEMS_PANE,
    TDLM_ITEM_BUTTONS_PANE,
    TDLM_ADD_ITEM_BUTTON,
    TDLM_REMOVE_ITEM_BUTTON,
    TDLM_EDIT_ITEM_BUTTON,
    TDLM_MOVE_UP_BUTTON,
    TDLM_MOVE_DOWN_BUTTON,
    TDLM_ITEMS_TABLE_VIEW,
    TDLM_NAME_COLUMN,
    TDLM_TYPE_COLUMN,
    TDLM_ORDER_COLUMN,
    TDLM_ADD_TEXT_BUTTON,
    TDLM_ADD_IMAGE_BUTTON,
    TDLM_ADD_RECTANGLE_BUTTON,
    TDLM_ADD_CIRCLE_BUTTON,
    TDLM_ADD_TRIANGLE_BUTTON,
    TDLM_DELETE_BUTTON,
    TDLM_FONT_BUTTON,
    TDLM_FONT_COMBO_BOX,
    TDLM_FONT_SIZE_COMBO_BOX,
    
    TDLM_BOLD_BUTTON,
    TDLM_ITALIC_BUTTON,
    TDLM_DOUBLE_SIZE_BUTTON,
    TDLM_HALF_SIZE_BUTTON,
    TDLM_FONT_COLOR_PICKER,
    TDLM_FOUCS_ANGLE_Slider,
    TDLM_BORDER_THICKNESS_Slider,
    TDLM_BORDER_RADIUS_Slider,
    TDLM_BORDER_COLOR_COLOR_PICKER,
    TDLM_CYCLE_METHOD_COMBO_BOX,
    TDLM_STEP_0_COLOR_COLOR_PICKER,
    TDLM_STEP_1_COLOR_COLOR_PICKER,
    
    
    
    
    
    
    
    // FOOLPROOF SETTINGS
    TDLM_FOOLPROOF_SETTINGS,
    
    // DIALOG CONTROLS
    TDLM_ITEM_DIALOG_HEADER,
    TDLM_ITEM_DIALOG_ADD_HEADER_TEXT,
    TDLM_ITEM_DIALOG_EDIT_HEADER_TEXT,
    TDLM_ITEM_DIALOG_CATEGORY_PROMPT,
    TDLM_ITEM_DIALOG_CATEGORY_TEXT_FIELD,
    TDLM_ITEM_DIALOG_DESCRIPTION_PROMPT,
    TDLM_ITEM_DIALOG_DESCRIPTION_TEXT_FIELD,
    TDLM_ITEM_DIALOG_START_DATE_PROMPT,
    TDLM_ITEM_DIALOG_START_DATE_PICKER,
    TDLM_ITEM_DIALOG_END_DATE_PROMPT,
    TDLM_ITEM_DIALOG_END_DATE_PICKER,
    TDLM_ITEM_DIALOG_ASSIGNED_TO_PROMPT,
    TDLM_ITEM_DIALOG_ASSIGNED_TO_TEXT_FIELD,
    TDLM_ITEM_DIALOG_COMPLETED_PROMPT,
    TDLM_ITEM_DIALOG_COMPLETED_CHECK_BOX,
    TDLM_ITEM_DIALOG_CONFIRM_PANE,
    TDLM_ITEM_DIALOG_OK_BUTTON,
    TDLM_ITEM_DIALOG_CANCEL_BUTTON,
    
    // THIS IS THE EXPORT TEMPLATE FILE NAME
    TDLM_EXPORT_TEMPLATE_FILE_NAME,
    
    //HOME TOOLBAR
    HAS_HOME, HAS_ZOOM_IN,HAS_ZOOM_OUT,HAS_RESIZE, HAS_SNAP,
    HOME_BUTTON, ZOOM_IN_BUTTON,ZOOM_OUT_BUTTON,RESIZE_BUTTON,SNAP_BUTTON,SNAP_LABEL,
    
    
    //RESIZE DIALOG
    TDLM_ITEM_RESIZE_DIALOG_TITLE,
    TDLM_ITEM_RESIZE_DIALOG_HEADER,
    TDLM_ITEM_RESIZE_DIALOG_HEIGHT_PROMPT,
    TDLM_ITEM_RESIZE_DIALOG_WIDTH_PROMPT,
    TDLM_TEXT_DIALOG_TITLE,
    TDLM_OPEN_DIALOG_TITLE,
    TDLM_TEXT_DIALOG_CONTENT_LABEL,
    TDLM_WRONG_CONTENT_MESSAGE,
    
}